### ISSUE TITLE
Incorrect Error. "Invalid URL format", instead of something like "Invalid Package Name"

### ISSUE THREAD

**Issue by KevinMartin** [bower/registry-client#15]
Looks like the Registry Client is looking for a 400 and assuming something bad with the URL, when it is really the Package Name. I got the error when trying to register a package with capital letters in its name.

https://github.com/bower/registry-client/blob/master/lib/register.js#L43

**Comment by BenMann** [comment]
Super old issue and also the underlying 400 is intended as per naming spec.
Closing :grin:
